Create maven.yml
sweat-tek/SB-MAI-E20-2 pull request #27
Opened 2020-11-13 10:42 UTC by Mathiasbrix

2020-11-19 21:46 UTC, semol18 requested changes
Change the path in the maven.yml to the proper pom.xml file.
Like this "JHotDraw/pom.xml"

2020-11-19 21:46 UTC, semol18 commented on .github/workflows/maven.yml
> +      run: mvn -B package --file pom.xml
the path to the pom.xml is incorrect, it should read "run: mvn -B package --file JHotDraw/pom.xml".

2020-11-20 09:30 UTC, aleksander-GD commented
`name: Java CI with Maven

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: windows-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file JHotDraw/pom.xml`

runs-on needs both ubuntu.

2020-11-21 16:55 UTC, closed without merging

2020-11-21 16:56 UTC, Mathiasbrix commented
The file has already been added to the master branch.